name: Terraform-Plan-infra

on:
  push:
    branches:

      - main

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"  # Replace with your AWS region

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      id: init
      run: terraform init 

    - name: Copy Terraform files
      run: |
        cp -r c:\awspocproject\AWS-DevOps\.github\project-infra\modules/* $GITHUB_WORKSPACE/

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'push'
      run: terraform plan -no-color
